services:
  # ========================================
  # DEBUG
  # ========================================
  debug:
    image: curlimages/curl:latest
    container_name: debug
    platform: linux/amd64
    stdin_open: true
    tty: true
    networks:
      - external_net
      - dmz_net
      - internal_net
    entrypoint: ["sh"]

  # ========================================
  # EXTERNAL CLIENT AND SERVER
  # ========================================

  #Simula client esterno
  external_client:
    image: alpine:latest
    container_name: external-client
    platform: linux/amd64
    command: sh -c "while true; do sleep 3600; done"
    networks:
      - external_net


  # ========================================
  # PERIMETRAL DEFENSE
  # ========================================

  # Bastion host 
  bastion-host:
    image: binlab/bastion
    container_name: bastion-host
    platform: linux/amd64
    hostname: bastion-host
    restart: unless-stopped
    expose:
      - 22/tcp
    ports:
      - 22222:22/tcp
    environment:
      PUBKEY_AUTHENTICATION: "true"
      GATEWAY_PORTS: "false"
      PERMIT_TUNNEL: "false"
      X11_FORWARDING: "false"
      TCP_FORWARDING: "true"
      AGENT_FORWARDING: "true"
    volumes:
      - ./bastion-host/authorized_keys:/var/lib/bastion/authorized_keys:ro
      - ./bastion-host/ssh:/usr/etc/ssh:rw
    extra_hosts:
      - docker-host:172.17.0.1
    networks:
      - dmz_net

  # Squid Proxy (forward proxy in DMZ)
  squid-proxy:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    platform: linux/amd64
    ports:
      - "3128:3128"
    networks:
      - dmz_net
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    command: squid -N -d 1

  # ========================================
  # AUTHENTICATION SYSTEM
  # ========================================

  # Keycloak (IdP per autenticazione)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    platform: linux/amd64
    command:
      - start-dev
      - --http-enabled=true
      # Admin ingresso http su 8081
      # Scambio token https su 8443
      - --http-port=8081
      - --https-port=8443
      - --hostname-strict=false
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # Essenziali per fare in modo che si abiliti https
      - KC_HTTPS_CERTIFICATE_FILE=/etc/keycloak/certs/server.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/keycloak/certs/server.key
      - KC_PROXY=edge
    volumes:
      #Preso lo stesso certificato di envoy (solo proof of concept)
      - ./authorization-system/envoy/secrets/certs:/etc/keycloak/certs
      - ./authentication-system/keycloak/data/h2:/opt/keycloak/data/h2
    ports:
      - "8081:8081"
      - "8443:8443"
    networks:
      - dmz_net
      
  keycloak-listener:
    build:
      context: ./authentication-system/keycloak-listener
      dockerfile: Dockerfile
    container_name: keycloak-listener
    platform: linux/amd64
    environment:
      KEYCLOAK_BASE: "http://keycloak:8081"
      KEYCLOAK_REALM: "zerotrust"
      KEYCLOAK_ADMIN_USER: "admin"
      KEYCLOAK_ADMIN_PASS: "admin"
      TRUST_URL: "http://trust-service:5000/event"
    depends_on:
      - keycloak
      - trust-service
    networks:
      - internal_net
      - dmz_net

  # ========================================
  # AUTHORIZATION SYSTEM
  # ========================================

  # Envoy Proxy (PEP)
  pep-envoy:
    build: ./authorization-system/envoy/compose
    container_name: pep-envoy
    # Stranamente envoy non interpreta le variabili d'ambiente :(
    platform: linux/amd64
    environment:
      - DEBUG_LEVEL=info
      - SERVICE_NAME=internal-service
      - SERVICE_PORT=8080
      # Varibili necessarie per la configurazione di Secret Discovery Service (SDS)
      - SERVICE_NODE=node1
      - SERVICE_CLUSTER=cluster1
    volumes:
      - ./authorization-system/envoy/envoy.yaml:/config/envoy.yaml
      - ./authorization-system/envoy/secrets/oauth-token-secret.yaml:/etc/envoy/oauth-token-secret.yaml
      - ./authorization-system/envoy/secrets/oauth-hmac-secret.yaml:/etc/envoy/oauth-hmac-secret.yaml
      - ./authorization-system/envoy/secrets/certs:/etc/envoy/certs
    networks:
      - internal_net
      - dmz_net
      - prod_net
      - dev_net
    ports:
      - "10000:10000"   # HTTP → redirect
      - "10001:10001"   # HTTPS → OAuth2/ExtAuthz/Router
      - "10002:10002"   # Admin 
  # OPA (PDP)
  pdp-opa:
    image: openpolicyagent/opa:latest-envoy
    container_name: pdp-opa
    platform: linux/amd64
    networks:
      - internal_net
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
      # Per passare gli header

      - "--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.response"
      - "--set=decision_logs.console=true"
      - "/policies/policy.rego"
    volumes:
      - ./authorization-system/opa/policies:/policies:ro
    ports:
      - "9191:9191" # gRPC plugin port OPA -> Envoy gRPC

  #Calcola il livello di fiducia e dialoga con il db
  trust-service:
    build:
      context: ./authorization-system/trust-service
      dockerfile: Dockerfile
    container_name: trust-service
    platform: linux/amd64
    environment:
      # Utente predisposto, diverso dall'admin di Postgres
      DATABASE_URL: "postgresql://trust_user:trust_pass@postgres:5432/companydb"
      T_SCALE_MINUTES: "1440" # default: 1 giorno
      PORT: "5000"
    networks:
      - internal_net
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  # Postgres (DBMS interno)
  postgres:
    image: postgres:latest
    container_name: postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: companydb
    networks:
      - internal_net
    ports:
      - "5432:5432"
    volumes:
      - ./authorization-system/postgres/data:/var/lib/postgresql/data
      - ./authorization-system/postgres/init:/docker-entrypoint-initdb.d

  #Sito aziendale
  internal-service:
    build:
      context: ./internal-web-service
    image: internal-service:latest
    container_name: internal-service
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - dmz_net
    ports:
      - "8080:8080"
  #Per aggiungere healthcheck decommentare le righe sottostanti
  #healthcheck:
  #  test: ["CMD", "node", "healthcheck.js"]
  #  interval: 10s
  #  timeout: 3s
  #  retries: 5


  # ========================================
  # HOST WORKSTATIONS (Simulano PC aziendali)
  # ========================================

  


#====================== DA CONFIGURARE ======================
      
#SNORT
#SPLUNK
#FLUENTD

# ========================================
# NET
# ========================================
networks:
  external_net:
    driver: bridge
  dmz_net:
    driver: bridge
  internal_net:
    driver: bridge
  prod_net:
    driver: bridge
  dev_net:
    driver: bridge
