x-logging: &fluentd-logging
  logging:
    driver: fluentd
    options:
      fluentd-address: "fluentd:24224"  
      tag: "{{.Name}}.{{.ID}}"
      labels: "com.docker.compose.service,com.docker.compose.project"
      env: "ENV,ROLE"
      fluentd-async: "true"
      fluentd-retry-wait: "1s"
      fluentd-max-retries: "3"

services:
  # ========================================
  # DEBUG
  # ========================================
  debug:
    build: ./debug
    container_name: debug
    platform: linux/amd64
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - external_net
      - dmz_net
      - internal_net

  # ========================================
  # EXTERNAL CLIENT AND SERVER
  # ========================================

  
  allowed-server:
    build: ./external-services/allowed-server
    networks:
      - external_net
    ports:
      - "8090:80"

  blocked-server:
    build: ./external-services/blocked-server
    networks:
      - external_net
    ports:
      - "8091:80"


  #Simula client esterno
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    cap_add:
      - NET_ADMIN 
    networks:
      - external_net
    environment:
      - TZ=Europe/Rome
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    ports:
      - "5600:5800"
    volumes:
      - ./external-clients/config:/config:rw

  # ========================================
  # PERIMETRAL DEFENSE
  # ========================================


  # Envoy Proxy (PEP) + Firewall L7 (->esterno) + Firewall L3 (->interno)
  pep-envoy:
    <<: *fluentd-logging
    build: ./authorization-system/envoy/compose
    container_name: pep-envoy
    # Stranamente envoy non interpreta le variabili d'ambiente :(
    platform: linux/amd64
    environment:
      - TZ=Europe/Rome
      - DEBUG_LEVEL=info
      # Varibili necessarie per la configurazione di Secret Discovery Service (SDS)
      - SERVICE_NODE=node1
      - SERVICE_CLUSTER=cluster1
    volumes:
      - ./authorization-system/envoy/envoy.yaml:/config/envoy.yaml
      - ./authorization-system/envoy/secrets/oauth-token-secret.yaml:/etc/envoy/oauth-token-secret.yaml
      - ./authorization-system/envoy/secrets/oauth-hmac-secret.yaml:/etc/envoy/oauth-hmac-secret.yaml
      - ./authorization-system/envoy/secrets/certs:/etc/envoy/certs
    networks:
      external_net:
        ipv4_address: 10.20.0.100
      dmz_net:
        ipv4_address: 10.21.0.100
      internal_net:
        ipv4_address: 10.22.0.100
      prod_net:
        ipv4_address: 10.23.0.100
      dev_net:
        ipv4_address: 10.24.0.100
    ports:
      - "10000:10000"   # HTTP → redirect to 10001
      - "10001:10001"   # HTTPS → OAuth2/ExtAuthz/Router ingress
      - "10002:10002"   # Admin 
      - "10003:10003"   # HTTP → redirect to 10004
      - "10004:10004"   # HTTP egress (non esposto esternamente)
    depends_on:
      - fluentd

  # ========================================
  # AUTHENTICATION SYSTEM
  # ========================================

  # Keycloak (IdP per autenticazione)
  keycloak:
    <<: *fluentd-logging
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    platform: linux/amd64
    command:
      - start-dev
      - --http-enabled=true
      # Admin ingresso http su 8081
      # Scambio token https su 8443
      - --http-port=8081
      - --https-port=8443
      - --hostname-strict=false
      - --import-realm
    environment:
      - TZ=Europe/Rome
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # Essenziali per fare in modo che si abiliti https
      - KC_HTTPS_CERTIFICATE_FILE=/etc/keycloak/certs/server.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/keycloak/certs/server.key
      - KC_PROXY=edge
      # Per log
      - KC_EVENTS_ENABLED=true
      - KC_LOG=console                # dove scrivere (target)
      - KC_LOG_LEVEL_ORG_KEYCLOAK_EVENTS=DEBUG  # login riusciti visibili
    volumes:
      #Preso lo stesso certificato di envoy (solo proof of concept)
      - ./authorization-system/envoy/secrets/certs:/etc/keycloak/certs
      - ./authentication-system/keycloak/data/h2:/opt/keycloak/data/h2
    ports:
      - "8081:8081"
      - "8443:8443"
    networks:
      external_net:
        ipv4_address: 10.20.0.21
      dmz_net:
        ipv4_address: 10.21.0.21
      internal_net:
        ipv4_address: 10.22.0.21
      prod_net:
        ipv4_address: 10.23.0.21
      dev_net:
        ipv4_address: 10.24.0.21
    depends_on:
      - fluentd

  # ========================================
  # AUTHORIZATION SYSTEM
  # ========================================

 
  # OPA (PDP)
  pdp-opa:
    <<: *fluentd-logging
    image: openpolicyagent/opa:latest-envoy
    container_name: pdp-opa
    platform: linux/amd64
    networks:
      - internal_net
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
      # Per passare gli header

      - "--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.response"
      - "--set=decision_logs.console=true"
      - "/policies/policy.rego"
    volumes:
      - ./authorization-system/opa/policies:/policies:ro
    ports:
      - "9191:9191" # gRPC plugin port OPA -> Envoy gRPC
    depends_on:
      - fluentd

  #Calcola il livello di fiducia e dialoga con il db
  trust-service:
    <<: *fluentd-logging
    build:
      context: ./authorization-system/trust-service
      dockerfile: Dockerfile
    container_name: trust-service
    platform: linux/amd64
    environment:
      T_SCALE_MINUTES: "1440" # default: 1 giorno
      PORT: "5000"
    networks:
      - mgmt_net
      - internal_net
    ports:
      - "5000:5000"
    depends_on:
      - fluentd

  internal-service:
    <<: *fluentd-logging
    build:
      context: ./internal-web-service
    image: internal-service:latest
    container_name: internal-service
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - dmz_net
    ports:
      - "8080:8080"
    depends_on:
      - fluentd
  #Per aggiungere healthcheck decommentare le righe sottostanti
  #healthcheck:
  #  test: ["CMD", "node", "healthcheck.js"]
  #  interval: 10s
  #  timeout: 3s
  #  retries: 5


  # ========================================
  # HOST WORKSTATIONS (Simulano PC aziendali)
  # ========================================

  dev-host:
    <<: *fluentd-logging
    image: jlesage/firefox:latest
    container_name: dev-host
    environment:
      - TZ=Europe/Rome
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
    networks:
      - dev_net
    ports:
      - "5800:5800"   # noVNC: http://localhost:5800
    volumes:
      - ./hosts/dev-host/config:/config:rw
    depends_on:
      - fluentd
      

  prod-host:
    <<: *fluentd-logging
    image: jlesage/firefox:latest
    container_name: prod-host
    environment:
      - TZ=Europe/Rome
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
    networks:
      - prod_net
    ports:
      - "5700:5800"   # noVNC: http://localhost:5700
    volumes:
      - ./hosts/prod-host/config:/config:rw
    depends_on:
      - fluentd


  # ========================================
  # Management
  # ========================================
      
  # IDS - SNORT
  snort-ids:
    build:
      context: ./management/snort
      dockerfile: Dockerfile
    container_name: snort-ids
    network_mode: host 
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_RESOURCE
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./management/snort/snort.conf:/etc/snort/snort.conf:ro
      - ./management/snort/custom.rules:/etc/snort/rules/custom.rules:ro
      - snort-logs:/var/log/snort  #path dove salva i log snort
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    depends_on:
      - fluentd


  # SPLUNK
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      TZ: "Europe/Rome"
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: changeme123
      SPLUNK_ENABLE_HEC: "true"
      SPLUNK_HEC_TOKEN: "f276f7d2-1e16-4520-a999-a935a465299f"
      SPLUNK_HEC_PORT: "8088"
      SPLUNK_HEC_SSL: "false"
    ports:
      - "18000:8000"
      - "18088:8088"
      - "18089:8089"  # Management port
    networks:
       mgmt_net:
           ipv4_address: 10.25.0.10
    volumes:
      - splunk-data:/opt/splunk
      - ./management/splunk/splunk-apps/zt_base:/opt/splunk/etc/apps/
      - /var/lib/docker/containers:/containers:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - fluentd
  

  # FLUENTD
  fluentd:
    build: ./management/fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - mgmt_net
    restart: unless-stopped
    volumes:
      - ./management/fluentd/conf:/fluentd/etc:ro
      - ./management/fluentd/buffer:/fluentd/buffer
      - ./management/fluentd/state:/fluentd/state
      # Volume condiviso, legge i log di snort
      - snort-logs:/var/log/snort:ro 
    environment:
      - KEYCLOAK_BASE=http://keycloak:8081
      - KEYCLOAK_REALM=zerotrust
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASS=admin
      - KC_POLL_INTERVAL=10

# ========================================
# NET
# ========================================
networks:
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0/24
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.22.0.0/24
  prod_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.0.0/24
  dev_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.24.0.0/24
  mgmt_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.25.0.0/24

volumes:
  snort-logs:
    driver: local
  splunk-data: